singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest
  storage:
    capacity: 5Gi

hub:
  db:
    type: postgres
    url: postgresql://postgres:yourpassword@postgresql:5432/jupyterhub
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

proxy:
  service:
    type: ClusterIP
  https:
    enabled: false

ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  hosts:
    - jupyter.local
  pathSuffix: ""
  pathType: Prefix