apiVersion: batch/v1
kind: Job
metadata:
  name: create-mlflow-db
  namespace: jupyter
spec:
  template:
    spec:
      containers:
      - name: mlflow-db-init
        image: python:3.10
        env:
        - name: PGPASSWORD
          value: "yourpassword"
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y postgresql-client
          until pg_isready -h postgresql -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          psql -h postgresql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'mlflowdb'" | grep -q 1 || psql -h postgresql -U postgres -c "CREATE DATABASE mlflowdb"
          echo "Database mlflowdb ready"
          pip install mlflow psycopg2-binary
          # Let MLflow initialize the schema automatically
          mlflow server --backend-store-uri postgresql://postgres:yourpassword@postgresql.jupyter.svc.cluster.local:5432/mlflowdb --default-artifact-root /tmp/artifacts --host 0.0.0.0 --port 5000 &
          sleep 10
          pkill -f mlflow
          echo "MLflow database initialized"
      restartPolicy: Never
  backoffLimit: 3