apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clearml-fileserver-data
  namespace: clearml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
