singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest

  cpu:
    guarantee: 1
    limit: 6
  memory:
    guarantee: 1G
    limit: 8G

  storage:
    capacity: 5Gi
  extraEnv:
    MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
    MINIO_ACCESS_KEY: "minioadmin"
    MINIO_SECRET_KEY: "minioadmin"
  networkPolicy:
    enabled: false
  # Ensure proper DNS resolution
  extraAnnotations:
    # Force DNS to use cluster DNS
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

hub:
  db:
    type: postgres
    url: postgresql://postgres:yourpassword@postgresql:5432/jupyterhub
  config:
    JupyterHub:
      authenticator_class: dummy
  podSecurityContext:
    runAsNonRoot: false
    fsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

proxy:
  service:
    type: ClusterIP
  https:
    enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - jupyter.local