singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest

  cpu:
    guarantee: 1
    limit: 6
  memory:
    guarantee: 1G
    limit: 8G

  storage:
    capacity: 5Gi
    extraVolumes:
      - name: clearml-config
        configMap:
          name: clearml-config
    extraVolumeMounts:
      - name: clearml-config
        mountPath: /etc/clearml/clearml.conf
        subPath: clearml.conf
        readOnly: true

  extraEnv:
    MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
    MINIO_ACCESS_KEY: 
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: MINIO_ACCESS_KEY
    MINIO_SECRET_KEY:
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: MINIO_SECRET_KEY
    CLEARML_API_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: clearml-credentials
          key: apiserver_key
    CLEARML_API_SECRET_KEY:
      valueFrom:
        secretKeyRef:
          name: clearml-credentials
          key: apiserver_secret
    CLEARML_CONFIG_FILE: /etc/clearml/clearml.conf
    
  networkPolicy:
    enabled: false
  extraAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

hub:
  db:
    type: postgres
    url: postgresql://postgres:yourpassword@postgresql:5432/jupyterhub
  config:
    JupyterHub:
      authenticator_class: dummy
  podSecurityContext:
    runAsNonRoot: false
    fsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

proxy:
  service:
    type: ClusterIP
  https:
    enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - jupyter.local