singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest
  storage:
    capacity: 5Gi
  # Add DNS configuration
  extraEnv:
    MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
    MINIO_ACCESS_KEY: "minioadmin"
    MINIO_SECRET_KEY: "minioadmin"
  networkPolicy:
    enabled: false
  # Ensure proper DNS resolution
  extraAnnotations:
    # Force DNS to use cluster DNS
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

hub:
  db:
    type: postgres
    url: postgresql://postgres:yourpassword@postgresql:5432/jupyterhub
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

proxy:
  service:
    type: ClusterIP
  https:
    enabled: false

ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  hosts:
    - jupyter.local
  pathSuffix: ""
  pathType: Prefix