# mlflow-values.yaml
# -------- MLflow Core --------
artifactRoot:
  s3:
    bucket: mlflow
    path: ""

# Environment variables for MinIO/S3 access
extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_S3_FORCE_PATH_STYLE: "true"
  BACKEND_STORE_URI: "postgresql://postgres:yourpassword@postgresql.jupyter.svc.cluster.local:5432/mlflowdb"

extraArgs:
  default-artifact-root: "s3://mlflow"
  backend-store-uri: "$(BACKEND_STORE_URI)"


service:
  type: ClusterIP
  port: 5000

# -------- Backend Store (Tracking DB) --------
backendStore:
  databaseConnectionCheck: false
 
# -------- Ingress --------
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: mlflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# -------- Resources --------
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

# -------- Security --------
serviceAccount:
  create: true
  name: ""

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}