# PostgreSQL configuration for minikube
auth:
  postgresPassword: yourpassword
  database: jupyterhub
  username: postgres

# Primary PostgreSQL configuration
primary:
  persistence:
    enabled: true
    storageClass: standard
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  
  # Disable security contexts for minikube compatibility
  podSecurityContext:
    enabled: false
  
  containerSecurityContext:
    enabled: false
  
  # Resource limits (optional, but good practice)
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 256Mi
      cpu: 250m

# Enable volume permissions fix for minikube
volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 128Mi
      cpu: 100m

# Metrics (optional - disable if you don't need them)
metrics:
  enabled: false

# Service configuration
service:
  type: ClusterIP
  ports:
    postgresql: 5432

# Initialize the jupyterhub database
primary:
  initdb:
    scripts:
      init.sql: |
        -- Ensure jupyterhub database exists
        SELECT 'CREATE DATABASE jupyterhub' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'jupyterhub')\gexec